### ISSUE TITLE
gem install error

### ISSUE THREAD

**Issue by otheus** [phemmer/ruby-corosync-commander#3]
```
~/ruby-corosync-commander-0.0.2# gem build corosync-commander.gemspec
WARNING:  no rubyforge_project specified
  Successfully built RubyGem
  Name: corosync-commander
  Version: 0.0.2
  File: corosync-commander-0.0.2.gem
~/ruby-corosync-commander-0.0.2# gem install corosync-commander-0.0.2.gem
Successfully installed corosync-commander-0.0.2
1 gem installed
Installing ri documentation for corosync-commander-0.0.2...
File not found: lib
~/ruby-corosync-commander-0.0.2# gem --version
1.3.7
```

Ah...

```
 gem install --no-ri --no-rdoc --local /root/ruby-corosync-commander-0.0.2/corosync-commander-0.0.2.gem
Successfully installed corosync-commander-0.0.2
1 gem installed
```

But wait!

```
~/ruby-corosync-commander-0.0.2# gem contents corosync-commander
~/ruby-corosync-commander-0.0.2#
```

So how do you install this thing?

**Comment by phemmer** [comment]
I'm thinking this is because of the rubygems version you're using. 1.3.7 is ancient, and the version of rubygems that comes with ruby-2.0 is also 2.0.

**Comment by otheus** [comment]
So it might be possible to use Ruby 1.8.7 but with a new version of Rubygems? (I'm a ruby-noob here)

**Comment by phemmer** [comment]
Unfortunately no. You might be able to install the gem, but it won't work. Due to the way corosync works, and limitations in ruby prior to 2.0, this gem will won't work with anything older.

**Comment by otheus** [comment]
OK, that's fine, but please mention that somewhere in the README. 
I have used rvm successfully in deploying Ruby 2.0 and have run the module in several test case scenarios. Thanking you very much. :)
