### ISSUE TITLE
Ruby 2.0 required?

### ISSUE THREAD

**Issue by otheus** [phemmer/ruby-corosync-commander#4]
If Ruby 2.0+ is required, this should be in the project README.

``` You cannot use this with MRI Ruby older than 2.0. Even with 2.0 you must tune ruby. This is because Corosync CPG (as of 1.4.3) allocates a 1mb buffer on the stack. Ruby 2.0 only allocates a 512kb stack for threads.```

**Comment by phemmer** [comment]
I have added this notice to the readme: https://github.com/phemmer/ruby-corosync-commander#ruby-stack-size
